/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "knative.dev/eventing-prometheus/pkg/apis/sources/v1alpha1"
)

// FakePrometheusRuleSources implements PrometheusRuleSourceInterface
type FakePrometheusRuleSources struct {
	Fake *FakeSourcesV1alpha1
	ns   string
}

var prometheusrulesourcesResource = v1alpha1.SchemeGroupVersion.WithResource("prometheusrulesources")

var prometheusrulesourcesKind = v1alpha1.SchemeGroupVersion.WithKind("PrometheusRuleSource")

// Get takes name of the prometheusRuleSource, and returns the corresponding prometheusRuleSource object, and an error if there is any.
func (c *FakePrometheusRuleSources) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PrometheusRuleSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(prometheusrulesourcesResource, c.ns, name), &v1alpha1.PrometheusRuleSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PrometheusRuleSource), err
}

// List takes label and field selectors, and returns the list of PrometheusRuleSources that match those selectors.
func (c *FakePrometheusRuleSources) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PrometheusRuleSourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(prometheusrulesourcesResource, prometheusrulesourcesKind, c.ns, opts), &v1alpha1.PrometheusRuleSourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PrometheusRuleSourceList{ListMeta: obj.(*v1alpha1.PrometheusRuleSourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.PrometheusRuleSourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested prometheusRuleSources.
func (c *FakePrometheusRuleSources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(prometheusrulesourcesResource, c.ns, opts))

}

// Create takes the representation of a prometheusRuleSource and creates it.  Returns the server's representation of the prometheusRuleSource, and an error, if there is any.
func (c *FakePrometheusRuleSources) Create(ctx context.Context, prometheusRuleSource *v1alpha1.PrometheusRuleSource, opts v1.CreateOptions) (result *v1alpha1.PrometheusRuleSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(prometheusrulesourcesResource, c.ns, prometheusRuleSource), &v1alpha1.PrometheusRuleSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PrometheusRuleSource), err
}

// Update takes the representation of a prometheusRuleSource and updates it. Returns the server's representation of the prometheusRuleSource, and an error, if there is any.
func (c *FakePrometheusRuleSources) Update(ctx context.Context, prometheusRuleSource *v1alpha1.PrometheusRuleSource, opts v1.UpdateOptions) (result *v1alpha1.PrometheusRuleSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(prometheusrulesourcesResource, c.ns, prometheusRuleSource), &v1alpha1.PrometheusRuleSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PrometheusRuleSource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePrometheusRuleSources) UpdateStatus(ctx context.Context, prometheusRuleSource *v1alpha1.PrometheusRuleSource, opts v1.UpdateOptions) (*v1alpha1.PrometheusRuleSource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(prometheusrulesourcesResource, "status", c.ns, prometheusRuleSource), &v1alpha1.PrometheusRuleSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PrometheusRuleSource), err
}

// Delete takes name of the prometheusRuleSource and deletes it. Returns an error if one occurs.
func (c *FakePrometheusRuleSources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(prometheusrulesourcesResource, c.ns, name, opts), &v1alpha1.PrometheusRuleSource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePrometheusRuleSources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(prometheusrulesourcesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PrometheusRuleSourceList{})
	return err
}

// Patch applies the patch and returns the patched prometheusRuleSource.
func (c *FakePrometheusRuleSources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PrometheusRuleSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(prometheusrulesourcesResource, c.ns, name, pt, data, subresources...), &v1alpha1.PrometheusRuleSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PrometheusRuleSource), err
}
