/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "knative.dev/eventing-prometheus/pkg/apis/sources/v1alpha1"
	scheme "knative.dev/eventing-prometheus/pkg/client/clientset/versioned/scheme"
)

// PrometheusRuleSourcesGetter has a method to return a PrometheusRuleSourceInterface.
// A group's client should implement this interface.
type PrometheusRuleSourcesGetter interface {
	PrometheusRuleSources(namespace string) PrometheusRuleSourceInterface
}

// PrometheusRuleSourceInterface has methods to work with PrometheusRuleSource resources.
type PrometheusRuleSourceInterface interface {
	Create(ctx context.Context, prometheusRuleSource *v1alpha1.PrometheusRuleSource, opts v1.CreateOptions) (*v1alpha1.PrometheusRuleSource, error)
	Update(ctx context.Context, prometheusRuleSource *v1alpha1.PrometheusRuleSource, opts v1.UpdateOptions) (*v1alpha1.PrometheusRuleSource, error)
	UpdateStatus(ctx context.Context, prometheusRuleSource *v1alpha1.PrometheusRuleSource, opts v1.UpdateOptions) (*v1alpha1.PrometheusRuleSource, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.PrometheusRuleSource, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.PrometheusRuleSourceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PrometheusRuleSource, err error)
	PrometheusRuleSourceExpansion
}

// prometheusRuleSources implements PrometheusRuleSourceInterface
type prometheusRuleSources struct {
	client rest.Interface
	ns     string
}

// newPrometheusRuleSources returns a PrometheusRuleSources
func newPrometheusRuleSources(c *SourcesV1alpha1Client, namespace string) *prometheusRuleSources {
	return &prometheusRuleSources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the prometheusRuleSource, and returns the corresponding prometheusRuleSource object, and an error if there is any.
func (c *prometheusRuleSources) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PrometheusRuleSource, err error) {
	result = &v1alpha1.PrometheusRuleSource{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("prometheusrulesources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PrometheusRuleSources that match those selectors.
func (c *prometheusRuleSources) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PrometheusRuleSourceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PrometheusRuleSourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("prometheusrulesources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested prometheusRuleSources.
func (c *prometheusRuleSources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("prometheusrulesources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a prometheusRuleSource and creates it.  Returns the server's representation of the prometheusRuleSource, and an error, if there is any.
func (c *prometheusRuleSources) Create(ctx context.Context, prometheusRuleSource *v1alpha1.PrometheusRuleSource, opts v1.CreateOptions) (result *v1alpha1.PrometheusRuleSource, err error) {
	result = &v1alpha1.PrometheusRuleSource{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("prometheusrulesources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(prometheusRuleSource).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a prometheusRuleSource and updates it. Returns the server's representation of the prometheusRuleSource, and an error, if there is any.
func (c *prometheusRuleSources) Update(ctx context.Context, prometheusRuleSource *v1alpha1.PrometheusRuleSource, opts v1.UpdateOptions) (result *v1alpha1.PrometheusRuleSource, err error) {
	result = &v1alpha1.PrometheusRuleSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("prometheusrulesources").
		Name(prometheusRuleSource.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(prometheusRuleSource).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *prometheusRuleSources) UpdateStatus(ctx context.Context, prometheusRuleSource *v1alpha1.PrometheusRuleSource, opts v1.UpdateOptions) (result *v1alpha1.PrometheusRuleSource, err error) {
	result = &v1alpha1.PrometheusRuleSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("prometheusrulesources").
		Name(prometheusRuleSource.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(prometheusRuleSource).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the prometheusRuleSource and deletes it. Returns an error if one occurs.
func (c *prometheusRuleSources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("prometheusrulesources").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *prometheusRuleSources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("prometheusrulesources").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched prometheusRuleSource.
func (c *prometheusRuleSources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PrometheusRuleSource, err error) {
	result = &v1alpha1.PrometheusRuleSource{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("prometheusrulesources").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
