# Copyright 2020 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Secret
metadata:
  name: prometheus-source-webhook-certs
  namespace: knative-eventing
  labels:
    app: prometheus-webhook
    app.kubernetes.io/component: prometheus-webhook
    app.kubernetes.io/version: devel
    app.kubernetes.io/name: knative-eventing
# The data is populated at install time.

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-webhook
  namespace: knative-eventing
  labels:
    app: prometheus-webhook
    knative.dev/high-availability: "true"
    app.kubernetes.io/component: prometheus-webhook
    app.kubernetes.io/version: devel
    app.kubernetes.io/name: knative-eventing
    bindings.knative.dev/exclude: "true"
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: prometheus-webhook
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels: *labels
    spec:
      serviceAccountName: prometheus-webhook
      containers:
        - name: prometheus-webhook
          terminationMessagePolicy: FallbackToLogsOnError
          image: ko://knative.dev/eventing-prometheus/cmd/webhook
          env:
          - name: SYSTEM_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CONFIG_LOGGING_NAME
            value: config-logging
          - name: METRICS_DOMAIN
            value: knative.dev/eventing
          - name: WEBHOOK_PORT
            value: "8443"
          - name: WEBHOOK_NAME
            value: prometheus-webhook
            # SINK_BINDING_SELECTION_MODE specifies the NamespaceSelector and ObjectSelector
            # for the sinkbinding webhook.
            # If `inclusion` is selected, namespaces/objects labelled as `bindings.knative.dev/include:true`
            # will be considered by the sinkbinding webhook;
            # If `exclusion` is selected, namespaces/objects labelled as `bindings.knative.dev/exclude:true`
            # will NOT be considered by the sinkbinding webhook.
            # The default is `exclusion`.
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name

          resources:
            requests:
              # taken from serving.
              cpu: 100m
              memory: 50Mi
            limits:
              # taken from serving.
              cpu: 200m
              memory: 200Mi

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault

          ports:
            - name: https-webhook
              containerPort: 8443
            - name: metrics
              containerPort: 9090
            - name: profiling
              containerPort: 8008

          readinessProbe:
            periodSeconds: 1
            httpGet:
              scheme: HTTPS
              port: 8443
              httpHeaders:
                - name: k-kubelet-probe
                  value: "webhook"
          livenessProbe:
            periodSeconds: 1
            httpGet:
              scheme: HTTPS
              port: 8443
              httpHeaders:
                - name: k-kubelet-probe
                  value: "webhook"
            initialDelaySeconds: 120
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-webhook
    app.kubernetes.io/component: prometheus-webhook
    app.kubernetes.io/version: devel
    app.kubernetes.io/name: knative-eventing
  name: prometheus-webhook
  namespace: knative-eventing
spec:
  ports:
    - name: https-webhook
      port: 443
      targetPort: 8443
  selector:
    app: prometheus-webhook
